version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle:
        applies-to: version-updates
        patterns: ["*"]
      gradle-security:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: version-updates
        patterns: ["*"]
      github-actions-security:
        applies-to: security-updates
        patterns: ["*"]
