/**
 * Classic-script body for the WebCrypto worker.
 * Kept as a string array so edits do not require backtick escaping (L-APP-04).
 * Consumed by crypto-worker.ts → Blob URL Worker from crypto.ts.
 */
const CRYPTO_WORKER_SOURCE_LINES: string[] = [
    "const CRYPTO_DB_NAME = 'app-crypto';",
    "const CRYPTO_STORE_NAME = 'keys';",
    "const LEGACY_CRYPTO_DB_NAME = 'saveable-crypto';",
    "const keyPromises = Object.create(null);",
    "let cryptoDbPromise = null;",
    "",
    "try { indexedDB.deleteDatabase(LEGACY_CRYPTO_DB_NAME); } catch (_error) {}",
    "",
    "function base64ToBytes(base64) {",
    "    const binary = atob(base64);",
    "    const bytes = new Uint8Array(binary.length);",
    "    for (let index = 0; index < binary.length; index += 1) {",
    "        bytes[index] = binary.charCodeAt(index);",
    "    }",
    "    return bytes;",
    "}",
    "",
    "function bytesToBase64(bytes) {",
    "    let binary = '';",
    "    for (let index = 0; index < bytes.length; index += 1) {",
    "        binary += String.fromCharCode(bytes[index]);",
    "    }",
    "    return btoa(binary);",
    "}",
    "",
    "function openDb(databaseName, version, storeName, keyPath) {",
    "    return new Promise((resolve, reject) => {",
    "        const request = indexedDB.open(databaseName, version);",
    "        request.onupgradeneeded = () => {",
    "            const db = request.result;",
    "            if (!db.objectStoreNames.contains(storeName)) {",
    "                db.createObjectStore(storeName, { keyPath });",
    "            }",
    "        };",
    "        request.onsuccess = () => resolve(request.result);",
    "        request.onerror = () => reject(request.error);",
    "    });",
    "}",
    "",
    "function idbGet(db, storeName, key) {",
    "    return new Promise((resolve, reject) => {",
    "        const transaction = db.transaction(storeName, 'readonly');",
    "        const request = transaction.objectStore(storeName).get(key);",
    "        request.onsuccess = () => resolve(request.result ?? null);",
    "        request.onerror = () => reject(request.error);",
    "    });",
    "}",
    "",
    "function idbPut(db, storeName, value) {",
    "    return new Promise((resolve, reject) => {",
    "        const transaction = db.transaction(storeName, 'readwrite');",
    "        transaction.oncomplete = () => resolve(true);",
    "        transaction.onerror = () => reject(transaction.error);",
    "        transaction.objectStore(storeName).put(value);",
    "    });",
    "}",
    "",
    "function openCryptoDb() {",
    "    if (cryptoDbPromise == null) {",
    "        cryptoDbPromise = openDb(CRYPTO_DB_NAME, 1, CRYPTO_STORE_NAME, 'id');",
    "    }",
    "    return cryptoDbPromise;",
    "}",
    "",
    "async function loadCryptoKey(keyAlias) {",
    "    if (keyPromises[keyAlias] != null) {",
    "        return keyPromises[keyAlias];",
    "    }",
    "    keyPromises[keyAlias] = (async () => {",
    "        const db = await openCryptoDb();",
    "        const existing = await idbGet(db, CRYPTO_STORE_NAME, keyAlias);",
    "        if (existing && existing.key) {",
    "            return existing.key;",
    "        }",
    "        const key = await crypto.subtle.generateKey(",
    "            { name: 'AES-GCM', length: 256 },",
    "            false,",
    "            ['encrypt', 'decrypt'],",
    "        );",
    "        await idbPut(db, CRYPTO_STORE_NAME, { id: keyAlias, key, createdAt: Date.now() });",
    "        return key;",
    "    })();",
    "    try {",
    "        return await keyPromises[keyAlias];",
    "    } catch (error) {",
    "        delete keyPromises[keyAlias];",
    "        throw error;",
    "    }",
    "}",
    "",
    "async function ensureKey(keyAlias) {",
    "    await loadCryptoKey(keyAlias);",
    "    return true;",
    "}",
    "",
    "async function encrypt(keyAlias, plaintextBase64, associatedDataBase64) {",
    "    const key = await loadCryptoKey(keyAlias);",
    "    const iv = crypto.getRandomValues(new Uint8Array(12));",
    "    const algorithm = { name: 'AES-GCM', iv: iv, tagLength: 128 };",
    "    if (associatedDataBase64 != null) {",
    "        algorithm.additionalData = base64ToBytes(associatedDataBase64);",
    "    }",
    "    const encryptedBuffer = await crypto.subtle.encrypt(algorithm, key, base64ToBytes(plaintextBase64));",
    "    const encrypted = new Uint8Array(encryptedBuffer);",
    "    const output = new Uint8Array(iv.length + encrypted.length);",
    "    output.set(iv, 0);",
    "    output.set(encrypted, iv.length);",
    "    return bytesToBase64(output);",
    "}",
    "",
    "async function decrypt(keyAlias, ciphertextBase64, associatedDataBase64) {",
    "    const key = await loadCryptoKey(keyAlias);",
    "    const input = base64ToBytes(ciphertextBase64);",
    "    if (input.length <= 12) {",
    "        throw new Error('Ciphertext too short.');",
    "    }",
    "    const iv = input.slice(0, 12);",
    "    const payload = input.slice(12);",
    "    const algorithm = { name: 'AES-GCM', iv: iv, tagLength: 128 };",
    "    if (associatedDataBase64 != null) {",
    "        algorithm.additionalData = base64ToBytes(associatedDataBase64);",
    "    }",
    "    const plainBuffer = await crypto.subtle.decrypt(algorithm, key, payload);",
    "    return bytesToBase64(new Uint8Array(plainBuffer));",
    "}",
    "",
    "self.onmessage = async (event) => {",
    "    const data = event.data;",
    "    const requestId = data.requestId;",
    "    const type = data.type;",
    "    const keyAlias = data.keyAlias;",
    "    try {",
    "        let result;",
    "        if (type === 'ensureKey') {",
    "            result = await ensureKey(keyAlias);",
    "        } else if (type === 'encrypt') {",
    "            result = await encrypt(keyAlias, data.plaintextBase64, data.associatedDataBase64 ?? null);",
    "        } else if (type === 'decrypt') {",
    "            result = await decrypt(keyAlias, data.ciphertextBase64, data.associatedDataBase64 ?? null);",
    "        } else {",
    "            throw new Error('Unknown crypto worker request type: ' + type);",
    "        }",
    "        self.postMessage({ requestId: requestId, ok: true, result: result });",
    "    } catch (error) {",
    "        const message = error instanceof Error ? error.message : String(error);",
    "        self.postMessage({ requestId: requestId, ok: false, error: message });",
    "    }",
    "};",
];

const cryptoWorkerSource = {
    cryptoWorkerScript: CRYPTO_WORKER_SOURCE_LINES.join('\n'),
};

export = cryptoWorkerSource;
